# Generated by Django 5.1.1 on 2024-09-28 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_course_video1'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_chptr',
            fields=[
                ('chapter_name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='media')),
                ('rating', models.CharField(max_length=1)),
                ('feedback', models.CharField(default=None, max_length=300)),
                ('course_name', models.ForeignKey(db_column='course_name', on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
        ),
    ]
