# Generated by Django 5.1.1 on 2024-09-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_course_chptr_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_chptr',
            name='chapter_name',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
