# Generated by Django 5.1.1 on 2024-09-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_paidfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidfeedback',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
