# Generated by Django 5.1.1 on 2024-10-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_chptr',
            name='notes_img',
            field=models.FileField(default=None, upload_to='media'),
        ),
    ]
